<a href="https://colab.research.google.com/github/mounta74/All-NeurIPS-papers_classification/blob/main/scratchpad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

a = np.random.randn(5, 1)

In [10]:
print(a)

[[ 0.90653524]
 [ 1.05798937]
 [-0.92916279]
 [ 0.09529277]
 [-0.05510579]]


In [11]:
print(a.shape)

(5, 1)


In [12]:
print(a.T)

[[ 0.90653524  1.05798937 -0.92916279  0.09529277 -0.05510579]]


In [13]:
print(np.dot(a, a.T))

[[ 0.82180615  0.95910465 -0.84231882  0.08638625 -0.04995534]
 [ 0.95910465  1.11934151 -0.98304435  0.10081873 -0.05830134]
 [-0.84231882 -0.98304435  0.86334349 -0.08854249  0.05120225]
 [ 0.08638625  0.10081873 -0.08854249  0.00908071 -0.00525118]
 [-0.04995534 -0.05830134  0.05120225 -0.00525118  0.00303665]]


In [14]:
b = np.dot(a, a.T)

In [15]:
print(b.shape)

(5, 5)


In [16]:
c = np.random.randn(5, 2)

In [17]:
print(c)

[[-1.38583152  0.25136093]
 [-0.64531435  0.19904015]
 [-1.73167337  0.10675001]
 [ 0.97396234  1.42516435]
 [ 1.8256538  -0.06146161]]


In [21]:
cc = np.dot(c.T, c)

In [22]:
cc.shape

(2, 2)

In [ ]:
a = np.random.randn(5, 1)

In [ ]:
a = np.random.randn(1, 5)

In [27]:
b = np.random.randn(5)

In [28]:
b = b.reshape((5, 1))

In [29]:
b

array([[ 0.74244205],
       [-0.21230284],
       [-0.69512749],
       [-1.07700183],
       [ 0.28236649]])